# Generated by Django 2.2.3 on 2019-09-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandOfShadowTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_code', models.CharField(max_length=100)),
                ('list_of_questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_questions', models.TextField()),
                ('list_of_answers', models.TextField()),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Planet')),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='sith_hand_of_shadow',
            field=models.ManyToManyField(to='main.Sith'),
        ),
    ]
