# Generated by Django 2.2.3 on 2019-09-17 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_code', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='HandOfShadowTask',
        ),
        migrations.AlterField(
            model_name='recruit',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='sith_hand_of_shadow',
            field=models.ManyToManyField(related_name='hand_of_shadow', to='main.Sith'),
        ),
        migrations.DeleteModel(
            name='TaskResult',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main.Recruit'),
        ),
    ]
