# Generated by Django 2.2.3 on 2019-09-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190917_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
    ]
